facts:
  has_relation(Article:_, String:project, Project:_):
    query: SELECT id, project FROM articles

  is_public(Article:_):
    query: SELECT id FROM articles WHERE is_public

sql_types:
  Article: bigint